#-------------------------------
# General Site Settings
title: Gitonga Miriam
logo: logo.svg # You can add own logo.
description: Gitonga Miriam


#-------------------------------
# Author Settings
author:
  name: Gitonga Miriam
  image: profile.jpeg
  say-hello: <strong>Hi</strong>, nice to meet you. 
  bio: I’m <strong>Gitonga Miriam</strong>. I love coming up with solutions to solve problems in society through IT as a Developer. I'm committed and results-driven fullstack developer and deep understanding of the software development Life Cycle. I have a history of repeated success in agile development from inception to excution by strategically allocating resources and delegating task to achieve on-time, on-budget delivery. Through running our family business which provides office workers with clothing and accessories. I accquired skills to enhance those that I learned in school. I am becoming a valuable engineer.


#-------------------------------
# Contact links
twitter: https://twitter.com/GitongaMiriam3/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
instagram: https://instagram.com/ # Add your Instagram handle
Github: https://github.com/Gitongamiriam/


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
